increase pull problem node runner timeout
JoyOI/VirtualJudge pull request #7
Opened 2017-11-13 12:36 UTC by shisoft

2017-11-13 12:55 UTC, yukozh approved these changes

2017-11-14 03:38 UTC, yukozh requested changes

2017-11-14 03:38 UTC, yukozh commented on src/JoyOI.VirtualJudge.LeetCode/LeetcodePullProblemBodyActor.cs
> +                TemplatesError = File.ReadAllText("stderr.txt"),
Please detect the runner exit code, if exit code is non-zero, please throw the exception, please don't return the body.

2017-11-14 03:39 UTC, yukozh commented on src/JoyOI.VirtualJudge.LeetCode/LeetcodePullProblemBodyActor.cs
> +                TemplatesError = File.ReadAllText("stderr.txt"),
Also, we don't have the field which named TemplatesError and Templates, please take a look into ProblemJson class in OnlineJudge repo.

2017-11-14 23:39 UTC, yukozh commented on src/JoyOI.VirtualJudge.LeetCode/LeetcodePullProblemBodyActor.cs
> +            var retryLeftTimes = 3;
What's the differences between the old and new?

2017-11-14 23:42 UTC, shisoft commented
Nothing, I think this is just formats

On 15 Nov 2017, 7:39 AM +0800, Yuko Zheng <notifications@github.com>, wrote:

@yukozh commented on this pull request.

________________________________

In src/JoyOI.VirtualJudge.LeetCode/LeetcodePullProblemBodyActor.cs<https://github.com/JoyOI/VirtualJudge/pull/7#discussion_r150996796>:

> -                File.WriteAllText("return.json", JsonConvert.SerializeObject(new { Outputs = returnFiles }));
-            }
-            catch (Exception ex)
-            {
-                --retryLeftTimes;
-                if (retryLeftTimes <= 0)
-                {
-                    File.WriteAllText("error.txt", ex.ToString());
-                    File.WriteAllText("return.json", JsonConvert.SerializeObject(new { Outputs = new[] { "error.txt" } }));
-                }
-                else
-                {
-                    await Task.Delay(3000);
-                    goto main;
-                }
+            var retryLeftTimes = 3;


What's the differences between the old and new?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/JoyOI/VirtualJudge/pull/7#pullrequestreview-76634062>, or mute the thread<https://github.com/notifications/unsubscribe-auth/ADP4PVVUM5Lrw3kDKTYmZyJpV_JwXM3hks5s2iSjgaJpZM4Qbso1>.

2017-11-15 00:16 UTC, yukozh commented
You still did not resolved the conflicts.

2017-11-15 03:18 UTC, merged

2017-11-15 06:12 UTC, shisoft commented
cuz I don't know how to do it on github. I can't make changes on this repo and the resolve button just don't work here